# Cloud Build to create and deploy Cloud Function for Historial Weather collection
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - fetch_historical_data
  - --entry-point=hello_fetch_historical_data
  - --region=europe-west1
  - --source=.
  - --trigger-topic=historical_weather_topic   
  - --runtime=python310
